# Generated by Django 5.1.4 on 2025-01-03 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresa', to='controle.endereco'),
        ),
    ]
