# Generated by Django 5.1.4 on 2024-12-31 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='entrada',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='É super usuário'),
        ),
    ]
